"""
Minimal nanodjango-bolt example with single-port serving.

Both Django views and BoltAPI routes are served on the same port by Actix.
Django views go through the ASGI bridge; BoltAPI routes are handled natively.

Run:
    uv run helloworld runbolt  # or use pipx instead of uvx

    OR,  if you have nanodjango bolt already installed in a python environment

    nanodjango manage helloworld.py runbolt

Then visit:
    http://localhost:8000/           (Django view)
    http://localhost:8000/api/hello  (Bolt API)
    http://localhost:8000/api/greet?name=World
"""
# /// script
# dependencies = [
#   "nanodjango-bolt @ git+https://github.com/cleemesser/nanodjango-bolt.git",
# ]
# ///
from nanodjango import Django
from nanodjango_bolt import BoltAPI

app = Django()
bolt = BoltAPI()


# this is a django route (wsgi)
@app.route("/")
def home(request):
    return r"""<h1>Hello, nanodjango-bolt!</h1>
    check out the autogenerated <a href="/docs/">api docs</a>
    <br> Invoke the api endpoints directly
    <p>Try <a href="/api/hello">/api/hello</a> or
         <a href="/api/greet?name=World">/api/greet?name=World</a></p>"""


# here are the bolt api routes


@bolt.get("/api/hello")
async def hello(request):
    return {"message": "hello from bolt"}


@bolt.get("/api/greet")
async def greet(name: str):
    return {"message": f"hello, {name}!"}


@bolt.post("/api/echo")
async def echo(msg: str):
    return {"you_sent": msg}


# Register catch-all AFTER all bolt routes so they take priority.
# Unmatched requests (like /) are forwarded to Django's ASGI app.

bolt.mount_django(r"/")

if __name__ == "__main__":
    import sys

    # needs to be imported after other things are configured
    # (single-file django app style)
    from django.core.management import (  # noqa: E402
        execute_from_command_line,
    )
    execute_from_command_line(sys.argv)
